### PR TITLE
Allow building on musl

### PR DESCRIPTION
**Pull request by prometheanfire**
Signed-off-by: Matthew Thode <mthode@mthode.org>

### CODE REVIEW

**Comment by prometheanfire** [comment]
If the entire block is moved out, it seems possible (including the original line).  Is that needed for this?

**Comment by prometheanfire** [comment]
I don't see a config.h to refactor this into (I think it's made by the configure script?)

**Comment by prometheanfire** [comment]
looks like autoreconf generates it, but I can't see a way to tell it additional content.

**Comment by reubenhwk** [comment]
It looks like the change in includes.h is good, but I don't want the same change in netlink.c.  Just include includes.h in netlink.c, remove the net/if.h include from netlink.c and I'll merge the pull request.

Please note how radvd puts the "" includes above the <> includes.  Follow that pattern.

**Pull request merged**
